grml/grml-etc-core

etc/zsh/zshrc
Host declaration may contain more than one pattern given after the
keyword, separated by whitespaces. For correct completion split the
string.
=> fix ssh remote host name completion with more than one pattern

etc/tmux.conf
This pull request removes the obsolete `mouse-select-pane` option from the tmux config.
Since the `mouse-select-pane` is deactivated in the config anyway and is off by default, this does not affect the current behaviour in any way. It does, however, fix the `unknown option: mouse-select-pane` warnings produced by tmux 2.1.
=> tmux: remove obsolete mouse-select-pane option

etc/zsh/zshrc
Output of `apt show` and `apt search` is more user-friendly,
so switch to it.
While at it fix description of `au` alias (it's apt and not
apt-get).
=> zshrc: use `apt` instead of `apt-get` also for search + show

etc/zsh/zshrc
Comment the obscure options ;
Add `ls -v` where available (natural sorting)
``` sh
$ touch 1 2 10; ls
1 10  2
$ ls -v
1  2 10
```
=> Adding a tiny bit to aliases

etc/zsh/zshrc
Starting with zsh version 5.1, ZLE began supporting "bracketed paste mode".
Currently, even on dumb terminals, ZLE sometimes emits the escape sequence "[?2004h" after the prompt if bracketed paste mode is not disabled. This prevents various tools that try to detect a shell prompt (such as Emacs TRAMP) from doing so successfully. (The shell prompt effectively becomes `user@host ~ % [?2004h` – which typically will not be matched by prompt detecting regexps, thereby breaking Emacs TRAMP for target hosts that use the Grml zsh config and zsh ≥5.1.)
Since most "dumb" terminals do not have bracketed paste capabilities anyway, this pull request changes the Grml zsh config to disable bracketed paste mode for "dumb" terminals.
=> Disable bracketed paste mode for dumb terminals

etc/grml/screenrc_generic
KDE's Konsole terminal sets env variable TERM to 'xterm-256color' by
default in newer versions, so the scrollbar fix did not match anymore.
---
This actually annoyed me for a long time now, and today I decided to do my research. I found the original solution at http://www4.cs.fau.de/~jnweiger/screen-faq.html and then realized it was all right there in grml's screenrc, only missing the little piece from this commit.
=> screenrc: Add 'xterm-256color' to terminals

etc/tmux.conf
From tmux 1.9, (20 Feb 2014), foo-{bg,fg,attr} commands have been
deprecated and tmux recommended to use foo-style instead.
Those options have been removed from tmux 2.9
It's more than 5 years from the deprecation of foo-{bg,fg,attr}.
it should be safe to use the new option by now.
Signed-off-by: Doan Tran Cong Danh <congdanhqx@gmail.com>
=> tmux: use foo-style to set status styles

etc/zsh/zshrc
It may be tempting to write a prompt token function like this
if (( ${+commands[kerl]} )) REPLY=$(kerl prompt '<%s> ')
But if the command does not exist user may be end up with duplicated
tokens in her prompt.  Resetting `$REPLY` parameter before calling
user-defined functions prevents this problem.
=> zshrc: Reset $REPLY parameter before calling prompt token functions

etc/zsh/zshrc
Prior to this change, when committing this line to history
echo "hello\"world"
zsh will record this line in history instead:
echo "hello"world"
because the \" is processed by print.
Correct it by print in raw mode.
Signed-off-by: Doan Tran Cong Danh <congdanhqx@gmail.com>
=> zsh: commit-to-history: keep escaped character

etc/zsh/zshrc
It's horribly annoying when PAGER is set to less, but lesspipe isn't configured
via LESSOPEN, then `dchange $package` fails with less like this:
% dchange zsh
"/usr/share/doc/zsh/changelog.Debian.gz" may be a binary file.  See it anyway?
vi(m) handles *.gz just fine, so let's try to use vi if PAGER is set to
less and LESSOPEN is unset.
While at it fix usage of ${PAGER} vs ${=PAGER} to also handle
a setting like PAGER='less -Mr' (otherwise failing with
`command not found: less -Mr`).
That's the best I could come up with for now without using vi by default and still supporting $PAGER. Any comments/better ideas?
=> zshrc: support PAGER='less -Mr' usage and fall back to vi if LESSOPEN is unset

etc/vim/vimrc
A lot of vimrc configuration options are Grml defaults since the very start of
the project. It is time to clean up as much as possible.
The configuration file (now) clones most of the settings taken from the
defaults.vim file which usually is only loaded if no user vimrc file is found
(see: :help defaults.vim).
The custom Grml configuration was reviewed, fixed and reformatted. The
configuration file should now be more readable and better maintainable.
=> vimrc: Major rework of the Grml configuration

etc/tmux.conf
Quoting the man page tmux(1) of v3.1b:
| Any other characters preceded by \ are replaced by themselves (that is,
| the \ is removed) and are not treated as having any special meaning - so
| for example \; will not mark a command sequence and \$ will not expand
| an environment variable.
and quoting the man page tmux(1) of v2.8:
| Each command should be separated by spaces and a semicolon; commands are
| executed sequentially from left to right and lines ending with a
| backslash continue on to the next line, except when escaped by another
| backslash.  A literal semicolon may be included by escaping it with a
| backslash (for example, when specifying a command sequence to bind-key).
This implies that a backslash should also be escaped by a backslash but
tmux still used to work with the …
=> tmux.conf: Fix unknown key: confirm-before error message

etc/tmux.conf
The previous change (see: c2cbdb01) tried to fix the error
"unknown key:  confirm-before".
Unfortunately that change only solved the problem for tmux v3.0+.
(Starting a new tmux session and reloading the configuration did not
bring up the error message in the older (<v3.0) tmux versions, so I
wrongly assumed that the change also worked for older versions.)
The changelog ("CHANGES FROM 2.9 to 3.0") states the following:
|  INCOMPATIBLE: tmux's configuration parsing has changed to use yacc(1). There
|  is one incompatible change: a \ on its own must be escaped or quoted as
|  either \\ or '\' (the latter works on older tmux versions).
|  Entirely the same parser is now used for parsing the configuration file
|  and for string commands. This means that constructs previously only
|  available …
=> tmux.conf: Fix /etc/tmux.conf:19: unknown key: \\ error message

etc/zsh/zshenv, etc/zsh/zshrc
The hostname binary doesn't necessarily exist, while
hostnamectl is available.
Closes: grml/grml-etc-core#96
=> zshsrc: support hostnamectl iff hostname isn't present

etc/zsh/zshrc
The batterydarwin function looks for the info it wants using field
numbers that are off by one on the current version of Mac OS.  I'm not
sure which version this changed in or what exactly they added (I suspect
it is the battery ID), but this patch makes battery info start working
again.
=> zshrc:  Fix darwin battery info field selection

etc/vim/vimrc
If vim-tiny is present (lacking +eval feature, see `vim --version`),
then invoking vim fails with:
| Error detected while processing /usr/share/vim/vimrc:
| line   30:
| E319: Sorry, the command is not available in this version: let g:skip_defaults_vim=1
The file /usr/share/vim/vimrc is a symlink to /etc/vim/vimrc:
| % ls -la /usr/share/vim/vimrc
| lrwxrwxrwx 1 root root 14 May 12 02:37 /usr/share/vim/vimrc -> /etc/vim/vimrc
So if the eval feature is missing, don't set skip_defaults_vim=1.
Furthermore, on older vim versions we're failing with:
| Error detected while processing /code/etc/vim/vimrc:
| line   61:
| E474: Invalid argument: display=truncate
| line  201:
| E474: Invalid argument: listchars=eol:$,precedes:«,extends:»,tab:»·,trail:·
The "set display=truncate" only works as of …
=> vimrc: support vim-tiny and older versions of vim

etc/zsh/zshrc
More distros move to zst as pkg compression format (such as archlinux), so add zst support
=> modified: etc/zsh/zshrc, add zstd support for simple-extract().

etc/zsh/zshenv, etc/zsh/zshrc
There's no need to invoke `hostname` or `hostnamectl --static`
when `uname -n` is POSIX.
Thanks: Darshaka Pathirana and Chris Hofstaedtler
Closes: grml/grml-etc-core#100
=> zshrc: rely only on `uname -n` for $HOSTNAME handling

etc/zsh/zshrc
Provide a simple way to connect to the running Grml system via tmate
by encoding the tmate ssh session in a QR code which can be scanned and
sent to the remote support side.
=> zshrc: add function grml-remote-support

etc/zsh/zshrc
This feature got lost in commit 08ab5d9, but nobody really noticed
this until we got annoyed by the sad-smiley on the right sight of the
prompt (rprompt) and wanted to disable the smiley overall. :)
But once the transient_rprompt option is active, the annoying
c/p behavior with the sad-smiley no longer exists, while
the feature is still there.
FTR, the rprompt in the grml prompt can be disabled e.g. with:
zstyle ':prompt:grml:right:setup' use-rprompt false
Thanks: Frank Terbeck
Closes: grml/grml-etc-core#107
=> zshrc: enable transient_rprompt to fix sad-smiley situation in rprompt

etc/zsh/zshrc
[Alacritty](https://github.com/alacritty/alacritty) is a “cross-platform, GPU-accelerated terminal emulator” written in Rust. By default, its window title is “Alacritty”. Since its `TERM` value is `alacritty`, zsh with the grml zshrc does not set the window title. This PR adds `alacritty` to the supported `TERM`s for setting the window title.
=> zshrc: set title in alacritty

etc/zsh/zshrc
[`lrzip`](https://github.com/ckolivas/lrzip) is a compression tool optimised for large files by combining standard compression with long-distance redundancy reduction. It is supported by libarchive (aka bsdtar). This patch allows `simple-extract` to identify and extract lrzip archives.
=> zshrc: add lrzip support for simple-extract()

etc/zsh/zshrc
url-quote with zsh >=5.1 does no longer work as such, it depends
on bracketed-paste-magic to work as it used to do
See https://github.com/zsh-users/zsh/blob/68405f31a043bdd5bf338eb06688ed3e1f740937/README#L38-L45
and https://archive.zhimingwang.org/blog/2015-09-21-zsh-51-and-bracketed-paste.html#update
and https://github.com/sorin-ionescu/prezto/issues/978
/cc @ft @btittelbach @jkirk I'd appreciate a review whether this makes sense as such, thanks!
=> zshrc: url-quote-magic depends on bracketed-paste-magic since zsh 5.1

etc/zsh/zshrc
fix add 'sudo' plugin zsh-syntax-highlighting error
If not `sudo`, use `sudo-command-line` add
```sh
ls
sudo ls
```
If has `sudo`, use `sudo-command-line` remove
```
sudo ls
ls 
```
If use zsh plugin `zsh-syntax-highlighting`, run `sudo-command-line` this color error. need `reset-prompt`
=> zshrc: change sudo-command-line switch 'sudo'

etc/zsh/zshrc
Futher improve #105 . There is another place using hostname[ctl].
=> remove dependency of hostname[ctl]

etc/zsh/zshrc
Some terminal emulators set COLORTERM=truecolor, do not overwrite those.
Closes: #131
=> zshrc: do not unconditionally overwrite $COLORTERM

doc/grmlzshrc.t2t, etc/zsh/zshrc
`/etc/hosts` may be used as a denylist for undesired hosts on some systems.
In such usage scenarios the file may be large in size and parsing it may severely impact shell startup time.
For example, on a system with `/etc/hosts` from https://github.com/StevenBlack/hosts:
```zsh
% cat profile.zsh
#!/usr/bin/env zsh
zmodload zsh/zprof
source ./etc/zsh/zshrc
zprof
```
```
% ./profile.zsh | head -3
num  calls                time                       self            name
-----------------------------------------------------------------------------------
1)    1        1181.93  1181.93   87.91%   1181.14  1181.14   87.85%  grmlcomp
```
```
% NOETCHOSTS=1 ./profile.zsh | head -3
num  calls                time                       self            name …
```
=> zshrc: add `NOETCHOSTS` parameter

etc/zsh/zshrc
This reduces cpu cycles, but interface `lo` has to be available
for the check to succeed.
=> zshrc: make ip touch interface lo only

etc/zsh/zshrc
This significantly improves the loading times of the grml zshrc file in
the case a user decides to block ads/tracking system-wide through the
use of a hosts file where tracking domains are blocked as such:
`0.0.0.0 trackingdomain.com`
Closes #118 
(Note: I'm not too familliar with the syntax used when setting up the _etc_hosts variable, I may have made a mistake here)
Signed-off-by: Atrate <Atrate@protonmail.com>
=> Ignore hosts set to invalid/loopback addresses for $_etc_hosts 

etc/tmux.conf
To manage a user-specific local configuration file (like in Grml's
'.vimrc.conf' + '.zshrc.conf') we need to source '~/.tmux.conf.local'.
"bind-key R" (Reload Config) does now reload the 'main" config file
'\~/.tmux.conf' and the user-specific local configuration file
'~/.tmux.conf.local'.
With 'source-file -q', no error will be returned if the file does not exist.
=> tmux.conf: source user-specific local conf file ~/.tmux.conf.local

etc/tmux.conf
We have "bind-key j" which joins "the last active pane to the currently
active window". This is cool, if you are able to directly jump to the
window where the pane should go to. Old people like me do not remember
the window (number) where they came from and skim around until they find
the window in question, try to remember the window number, jump back and
forth from window with the needed pane and finally "join the last active
pane to the currently active window".
This is a bit cumbersome, but with "bind-key m" it is possible to
mark the pane in question, skim around until one fine the window where
the pane belongs and "join the marked pane to the currently active
window".
=> tmux.conf: Add bind-key J to join marked pane to active window

etc/zsh/zshrc
=> Fix a typo in `zshrc`

doc/grmlzshrc.t2t, etc/zsh/zshrc
It's annoying to follow the syslog, but then tools like logroate kicking in to rename syslog to syslog.1. Then you're stuck with the "old" syslog file content, by using the --follow=name option we can fix this.
Quoting from tail(1):
```
With --follow (-f), tail defaults to following the file descriptor, which means that even
if a tail'ed file is renamed, tail will continue | to track its end. This default behavior
is not desirable when you really want to track the actual name of the file, not the
file descriptor (e.g., log rotation). Use --follow=name in that case. That causes tail
to track the named file in a way that accommodates renaming, removal and creation.
```
=> zshrc: run tlog alias with --follow=name

etc/tmux.conf
tmux versions >=2.3 support the -q option for source-file to suppress errors for nonexistent files. Even Debian/oldoldstable has tmux v2.3-4, so this works nice everwhere, *except* for when invoking tmate, which is a fork based on an old version of tmux, which then complains about:
| /etc/tmux.conf:75: usage: source-file path
| /etc/tmux.conf:36: usage: source-file path
Try to detect tmate from within the environment, and then enable the configuration only when *not* running from within tmate.
This commit relies on @mika's commit grml/grml-etc-core@71101e0 (the commit message was shamelessly copied, thx!), but two things changed:
* Use `! (env | grep -q TMUX=/tmp/tmate)` instead of `env | grep -q TMUX=/tmp/tmate && false` which always results in false:
$ true && false; echo $?
1
* Double …
=> tmux.conf: detect running as tmate and disable non-supported features

etc/skel/.zshrc
The file isn't properly encoded and claims to be latin1. Convert to UTF8 to avoid broken characters in getanchors().
Thanks: flobee for the bug report
Closes: https://github.com/grml/grml-etc-core/issues/155
=> etc/skel/.zshrc: set file encoding to UTF8

etc/zsh/zshenv
Various modern "language-level" package managers put programs they install into that directory.
=> zshenv: add ~/.local/bin to default PATH

etc/zsh/zshenv
http://bugs.debian.org/1064931
mknod should be used directly instead.
=> MAKEDEV is gone from Debian, drop WRITE_ON_UDEV

etc/zsh/zshrc
Otherwise it might be actually unexpected for some users of the Grml live system, so use same defaults for live system as for non-live systems.
While at it, switch to the foo=${foo:-default} style as suggested by Frank Terbeck in https://github.com/grml/grml-etc-core/issues/160 - thanks!
FTR: maybe we want to even further increase the defaults? (Personally I've set it to `10000000` on my own systems, not sure it's relevant memory wise or so?)
=> zshrc: increase HISTSIZE + SAVEHIST to our defaults also for live system

doc/grmlzshrc.t2t, etc/zsh/zshrc
In commit 7465ffb0803b0eb05d808b850088e90572c8dacd we adjusted the behavior when HISTSIZE and/or SAVEHIST are unset. Though this broke existing setups where HISTSIZE and SAVEHIST was not yet set (like in /etc/profile.d as reported in #160), as zsh sets HISTSIZE and SAVEHIST by default:
```
config.h.in:#define DEFAULT_HISTSIZE 30
configure.ac:#define DEFAULT_HISTSIZE 30
```
So `zsh -f` defaults to $HISTSIZE of 30 and $SAVEHIST of 0, Now we clearly want to ship better defaults than this. Do this, by checking whether is HISTSIZE is unset or set to the upstream default (being 30), only then set HISTSIZE and SAVEHIST.
In commit 81096c8f57c088163cfcea49f2eb03b4b44c66fd we increased HISTSIZE + SAVEHIST also for our live system usage, re-apply this change.
Closes: …
=> zshrc: set HISTSIZE + SAVEHIST only if not yet set or being set to zsh upstream default

etc/zsh/zshenv
Assume that people using distcc can and want to configure it themselves.
This was set in `zshenv`, which we need to tidy up.
=> Drop DISTCC_HOSTS variable

doc/grmlzshrc.t2t, etc/zsh/zshrc
The target program (hg-buildpackage) does not exist anymore.
=> zshrc: remove "hbp" alias

doc/grmlzshrc.t2t, etc/zsh/zshrc
It was introduced in commit 3d6452fdfc44310b5615eaf61c95cab4c27d9bf8 in 2007, and 724508d30c788da653579d44ac3566f27ffed1d6 in 2008 tried to remove it. The remove was reverted in 347c7def8583733dd8f8440214af25fbaf89666f in 2008.
Let's try this again, this time with a deprecation warning.
Addresses #183.
=> zshrc: deprecate xunfunction

etc/zsh/zshrc
* aptitude and grep-execuses(devscripts) might not be installed so we don't have any use of these aliases in that case.
=> etc/zsh/zshrc: only alias if command is present

etc/zsh/zshrc
TBH: I am not sure about the `#a2#` tag in the comment above. I just copied the comment from above.
The comment for `#a#` is not perfectly clear for me:
https://github.com/grml/grml-etc-core/blob/e2a5cafd7db6c24c72cac370bb073850b0a762f7/etc/zsh/zshrc#L42-L45
=> zshrc: Add alias llblk for lsblk with useful columns

etc/zsh/zshrc
This continues to rely on sysvinit compatibility bits, but this can be fixed later.
Closes: grml/grml-etc-core#199
=> zshrc: drop sv support from init.d functions

etc/zsh/zshrc
Previously only LANG LC_ALL LC_MESSAGES were exported. I assume the historic reason is that grml-setlang used to set up exactly these three variables in /etc/default/locale. With the new grml-setlang changes LC_COLLATE LC_TIME can also be set. Lets support all variables so this is not specific to grml-setlang.
=> zshrc: export all locale variables

debian/grml-etc-core.maintscript
Removed in 5b64711912051504b84cce8ab028a6a26bd58948.
=> Unregister /etc/network/interfaces.examples as a conffile

doc/grmlzshrc.adoc, etc/zsh/zshrc
Hopefully everybody has migrated to UTF-8 systems. Grml Live has removed support for non-UTF-8.
=> Remove iso2utf/utf2iso and term2iso/term2utf

doc/grmlzshrc.adoc, etc/zsh/zshrc
Since grml/grml-live#247 grml/grml-live@61be58509c5bbc5401806003bda83768818d552d the initial CWD is set by systemd to HOME.
The rungetty/autologin workaround can thus go away.
Closes: grml/grml-etc-core#180
=> Remove checkhome hack

etc/zsh/zshrc
While there, fix whitespace
--
```
root@fbsd ~ # which cdt
cdt () {
local -a cdttemplate
if [ "$#" -eq 1 ]
then
if isfreebsd
then
cdttemplate=(-t "$1") 
else
cdttemplate=(-t "$1".XXXXXXX) 
fi
fi
builtin cd "$(mktemp -d ${cdttemplate[@]})"
builtin pwd
}
root@fbsd ~ # cdt grml
/tmp/grml.YFIkcJQw71
root@fbsd /tmp/grml.YFIkcJQw71 # uname -a
FreeBSD fbsd.local 14.2-RELEASE-p1 FreeBSD 14.2-RELEASE-p1 GENERIC amd64
```
Improves #203
=> zshrc: add special code for cdt() for FreeBSD

debian/grml-etc-core.manpages, debian/manpages
* debhelper didn't touch d/manpages in favour of d/grml-etc-core.manpages so we need to move all manpages to the later.
=> d/man fix missing grmlzshrc.5

doc/grmlzshrc.adoc, etc/zsh/zshrc
Used GNU screen. Probably users switched to tmux and/or mosh.
Fixes https://github.com/grml/grml-etc-core/issues/230
=> Remove "asc" function
